services:
  thor-solo:
    image: ghcr.io/vechain/thor:latest
    hostname: thor-solo
    container_name: thor-solo
    user: root
    environment:
      - DOCKER=1
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "apk update --no-cache && apk add --no-cache curl && thor solo --on-demand --persist --data-dir /data/thor --api-addr 0.0.0.0:8669 --api-cors '*' --verbosity 10",
      ]
    ports:
      - "8669:8669"
    healthcheck:
      test: curl --fail 0.0.0.0:8669/blocks/0 || exit 1
      interval: "2s"
      retries: 30
    volumes:
      - thor-data:/data/thor
    networks:
      - vechain-thor

  insight:
    image: ghcr.io/vechain/insight-app:master
    hostname: insight
    container_name: insight
    environment:
      - VUE_APP_SOLO_URL=http://localhost:8669
    ports:
      - "8086:80"
    networks:
      - vechain-thor

  inspector:
    image: ghcr.io/vechain/inspector-app:master
    hostname: inspector
    container_name: inspector
    environment:
      - VUE_APP_SOLO_URL=http://localhost:8669
    ports:
      - "8087:80"
    networks:
      - vechain-thor

  block-explorer:
    image: ghcr.io/vechain/block-explorer:latest
    container_name: block-explorer
    hostname: block-explorer
    environment:
      - NEXT_PUBLIC_IS_SOLO=true
      - NEXT_PUBLIC_SOLO_NODE_URL=http://localhost:8669
      - NEXT_PUBLIC_VEWORLD_INDEXER_SOLO_URL=http://localhost:8089
      - B32_URL=https://b32.vecha.in
    ports:
      - "8088:3000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/ || exit 1
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3
    depends_on:
      thor-solo:
        condition: service_healthy
    networks:
      - vechain-thor

networks:
  vechain-thor:
    driver: bridge
    name: vechain-thor
volumes:
  thor-data:
    driver: local
    name: thor-data
